#!/bin/bash
set -euo pipefail

sqlplus -S "${APP_USER}/${APP_USER_PASSWORD}@//localhost:1521/FREEPDB1" <<'EOSQL'
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE T_ORGANIZATION (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_NAME VARCHAR2(100),
    BUSINESS_NUMBER VARCHAR2(50) UNIQUE,
    INDUSTRY_TYPE VARCHAR2(50),
    EMPLOYEE_COUNT NUMBER,
    ADDRESS VARCHAR2(200),
    CONTACT_NAME VARCHAR2(50),
    CONTACT_EMAIL VARCHAR2(100),
    CONTACT_PHONE VARCHAR2(50),
    AGREEMENT_STATUS VARCHAR2(20),
    SUBMITTED_AT TIMESTAMP,
    APPROVED_AT TIMESTAMP,
    REVIEW_COMMENT VARCHAR2(1000),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE T_USER (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_ID NUMBER,
    LOGIN_ID VARCHAR2(50) UNIQUE,
    PASSWORD VARCHAR2(100),
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(50),
    ROLE VARCHAR2(20),
    STATUS VARCHAR2(20),
    LAST_LOGIN_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    CONSTRAINT FK_USER_ORGANIZATION
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES T_ORGANIZATION(ID)
);

CREATE TABLE T_EMPLOYEE (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_ID NUMBER,
    USER_ID NUMBER,
    EMPLOYEE_NO VARCHAR2(50),
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    DEPARTMENT VARCHAR2(100),
    POSITION VARCHAR2(50),
    EMPLOYMENT_STATUS VARCHAR2(20),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    CONSTRAINT FK_EMPLOYEE_ORGANIZATION
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES T_ORGANIZATION(ID),

    CONSTRAINT FK_EMPLOYEE_USER
    FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);

CREATE TABLE T_NOTIFICATION (
    ID NUMBER PRIMARY KEY,
    RECEIVER_USER_ID NUMBER,
    TYPE VARCHAR2(50),
    TITLE VARCHAR2(200),
    CONTENT VARCHAR2(1000),
    TARGET_ID NUMBER,
    IS_READ NUMBER(1) DEFAULT 0,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,

    CONSTRAINT FK_NOTIFICATION_USER
    FOREIGN KEY (RECEIVER_USER_ID) REFERENCES T_USER(ID)
);

CREATE TABLE T_STATION_USAGE_STAT (
    ID NUMBER PRIMARY KEY,
    STAT_DATE DATE,
    REGION_NAME VARCHAR2(100),
    STATION_NAME VARCHAR2(100),
    STATION_CODE VARCHAR2(50),
    RIDE_COUNT NUMBER,
    RETURN_COUNT NUMBER,
    COMMUTE_USAGE_COUNT NUMBER,
    CREATED_AT TIMESTAMP
);

CREATE TABLE T_DASHBOARD (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,

    TOTAL_RIDE_COUNT NUMBER,
    TOTAL_COMMUTE_COUNT NUMBER,
    CARBON_REDUCTION NUMBER,

    LAST_UPDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,

    CONSTRAINT FK_DASHBOARD_USER
    FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);

CREATE TABLE T_APPLICATION_FILE (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    ORIGINAL_FILE_NAME VARCHAR2(255),
    STORED_FILE_NAME VARCHAR2(255),
    FILE_PATH VARCHAR2(500),
    FILE_SIZE NUMBER,
    CONTENT_TYPE VARCHAR2(100),
    CREATED_AT TIMESTAMP,

    CONSTRAINT FK_FILE_USER
    FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);

CREATE INDEX IDX_USER_ORGANIZATION ON T_USER(ORGANIZATION_ID);
CREATE INDEX IDX_EMPLOYEE_ORGANIZATION ON T_EMPLOYEE(ORGANIZATION_ID);
CREATE INDEX IDX_NOTIFICATION_USER ON T_NOTIFICATION(RECEIVER_USER_ID);
CREATE INDEX IDX_DASHBOARD_USER ON T_DASHBOARD(USER_ID);

CREATE SEQUENCE organization_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE employee_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE notification_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE station_usage_stat_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE dashboard_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE application_file_seq START WITH 1 INCREMENT BY 1 NOCACHE;

EXIT;
EOSQL
