CREATE TABLE T_ORGANIZATION (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_NAME VARCHAR2(100),
    BUSINESS_NUMBER VARCHAR2(50) UNIQUE,
    INDUSTRY_TYPE VARCHAR2(50),
    EMPLOYEE_COUNT NUMBER,
    ADDRESS VARCHAR2(200),
    CONTACT_NAME VARCHAR2(50),
    CONTACT_EMAIL VARCHAR2(100),
    CONTACT_PHONE VARCHAR2(50),
    AGREEMENT_STATUS VARCHAR2(20),
    SUBMITTED_AT TIMESTAMP,
    APPROVED_AT TIMESTAMP,
    REVIEW_COMMENT VARCHAR2(1000),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE T_USER (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_ID NUMBER,
    LOGIN_ID VARCHAR2(50) UNIQUE,
    PASSWORD VARCHAR2(100),
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(50),
    ROLE VARCHAR2(20),
    STATUS VARCHAR2(20),
    LAST_LOGIN_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    CONSTRAINT FK_USER_ORGANIZATION
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES T_ORGANIZATION(ID)
);

CREATE TABLE T_EMPLOYEE (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_ID NUMBER,
    USER_ID NUMBER,
    EMPLOYEE_NO VARCHAR2(50),
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    DEPARTMENT VARCHAR2(100),
    POSITION VARCHAR2(50),
    EMPLOYMENT_STATUS VARCHAR2(20),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    CONSTRAINT FK_EMPLOYEE_ORGANIZATION
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES T_ORGANIZATION(ID),

    CONSTRAINT FK_EMPLOYEE_USER
    FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);

CREATE TABLE T_EMPLOYEE_USAGE_STAT (
    ID NUMBER PRIMARY KEY,
    ORGANIZATION_ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL,
    USAGE_DATE DATE NOT NULL,
    USAGE_COUNT NUMBER DEFAULT 0 NOT NULL,
    TRAVEL_DISTANCE NUMBER(12, 2) DEFAULT 0 NOT NULL,
    CARBON_AMOUNT NUMBER(12, 2) DEFAULT 0 NOT NULL,
    USAGE_DURATION_MINUTES NUMBER(12, 2) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT FK_EMPLOYEE_USAGE_STAT_ORGANIZATION
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES T_ORGANIZATION(ID),

    CONSTRAINT FK_EMPLOYEE_USAGE_STAT_EMPLOYEE
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE(ID)
);

CREATE TABLE T_NOTIFICATION (
    ID NUMBER PRIMARY KEY,
    RECEIVER_USER_ID NUMBER,
    TYPE VARCHAR2(50),
    TITLE VARCHAR2(200),
    CONTENT VARCHAR2(1000),
    TARGET_ID NUMBER,
    IS_READ NUMBER(1) DEFAULT 0,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,

    CONSTRAINT FK_NOTIFICATION_USER
    FOREIGN KEY (RECEIVER_USER_ID) REFERENCES T_USER(ID)
);

CREATE TABLE T_STATION (
    STATION_CODE VARCHAR2(50) PRIMARY KEY,
    STATION_NAME VARCHAR2(200) NOT NULL,
    DISTRICT_NAME VARCHAR2(100),
    DETAIL_ADDRESS VARCHAR2(300),
    LATITUDE NUMBER(10, 6),
    LONGITUDE NUMBER(10, 6),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE T_STATION_USAGE_STAT (
    ID NUMBER PRIMARY KEY,
    STAT_DATE DATE NOT NULL,
    STATION_CODE VARCHAR2(50) NOT NULL,
    RENTAL_TYPE VARCHAR2(50),
    GENDER VARCHAR2(20),
    AGE_GROUP VARCHAR2(20),
    USAGE_COUNT NUMBER DEFAULT 0 NOT NULL,
    EXERCISE_AMOUNT NUMBER(12, 2),
    CARBON_AMOUNT NUMBER(12, 2),
    TRAVEL_DISTANCE NUMBER(12, 2),
    USAGE_DURATION_MINUTES NUMBER(12, 2),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT FK_STATION_USAGE_STAT_STATION
    FOREIGN KEY (STATION_CODE) REFERENCES T_STATION(STATION_CODE)
);

CREATE TABLE T_DASHBOARD (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,

    TOTAL_RIDE_COUNT NUMBER,
    TOTAL_COMMUTE_COUNT NUMBER,
    CARBON_REDUCTION NUMBER,   -- 탄소 절감량

    LAST_UPDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,

    CONSTRAINT FK_DASHBOARD_USER
    FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);


CREATE TABLE T_APPLICATION_FILE (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    ORIGINAL_FILE_NAME VARCHAR2(255),
    STORED_FILE_NAME VARCHAR2(255),
    FILE_PATH VARCHAR2(500),
    FILE_SIZE NUMBER,
    CONTENT_TYPE VARCHAR2(100),
    CREATED_AT TIMESTAMP,

    CONSTRAINT FK_FILE_USER
    FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);

CREATE INDEX IDX_USER_ORGANIZATION ON T_USER(ORGANIZATION_ID);
CREATE INDEX IDX_EMPLOYEE_ORGANIZATION ON T_EMPLOYEE(ORGANIZATION_ID);
CREATE INDEX IDX_EMPLOYEE_USAGE_STAT_ORGANIZATION ON T_EMPLOYEE_USAGE_STAT(ORGANIZATION_ID);
CREATE INDEX IDX_EMPLOYEE_USAGE_STAT_EMPLOYEE ON T_EMPLOYEE_USAGE_STAT(EMPLOYEE_ID);
CREATE INDEX IDX_EMPLOYEE_USAGE_STAT_DATE ON T_EMPLOYEE_USAGE_STAT(USAGE_DATE);
CREATE INDEX IDX_EMPLOYEE_USAGE_STAT_ORG_DATE ON T_EMPLOYEE_USAGE_STAT(ORGANIZATION_ID, USAGE_DATE);
CREATE INDEX IDX_NOTIFICATION_USER ON T_NOTIFICATION(RECEIVER_USER_ID);
CREATE INDEX IDX_STATION_DISTRICT ON T_STATION(DISTRICT_NAME);
CREATE INDEX IDX_STATION_USAGE_STAT_DATE ON T_STATION_USAGE_STAT(STAT_DATE);
CREATE INDEX IDX_STATION_USAGE_STAT_STATION ON T_STATION_USAGE_STAT(STATION_CODE);
CREATE INDEX IDX_STATION_USAGE_STAT_DATE_STATION ON T_STATION_USAGE_STAT(STAT_DATE, STATION_CODE);
CREATE INDEX IDX_STATION_USAGE_STAT_DASHBOARD ON T_STATION_USAGE_STAT(STAT_DATE, STATION_CODE, USAGE_COUNT);
CREATE INDEX IDX_ORGANIZATION_STATUS_SUBMITTED ON T_ORGANIZATION(AGREEMENT_STATUS, SUBMITTED_AT, ID);
CREATE INDEX IDX_DASHBOARD_USER ON T_DASHBOARD(USER_ID);

CREATE SEQUENCE organization_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE employee_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE employee_usage_stat_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE notification_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE station_usage_stat_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE dashboard_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE application_file_seq START WITH 1 INCREMENT BY 1 NOCACHE;
